config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'plays#index'

  resources :plays do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :plays

  scope :list_all_for_options, -> { Category.all.map { |c| [c.name, c.id] } }
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [250, 350]
  end

  validates :image, content_type: %w[image/png image/jpg image/jpeg image/webp], size: {
    less_than: 2.megabytes, message: 'must be less than 2MB'
  }

  scope :by_category, ->(category) { where(category_id: category) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :play
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plays
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit]
  before_action :set_play, only: %i[show edit update destroy]
  before_action :set_categories, only: %i[new edit create update]

  def index
    if params[:category]
      category = Category.find_by(name: params[:category])
      @plays = Play.by_category(category)
    else
      @plays = Play.all.order(created_at: :desc)
    end
  end

  def show
    return @average_review = 0 if @play.reviews.blank?

    @average_review = @play.reviews.average(:rating).round(2)
    @half_star = true if @average_review.to_s.split('.').last != '0'
  end

  def new
    @play = current_user.plays.build
  end

  def edit
  end

  def create
    @play = current_user.plays.build(play_params)

    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @play.category_id = params[:category_id]

    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render :edit
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def set_play
    @play = Play.find(params[:id])
  end

  def set_categories
    @categories = Category.list_all_for_options
  end

  def play_params
    params.require(:play).permit(:title, :description, :director, :category_id, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit]
  before_action :set_play
  before_action :set_review, only: %i[edit update destroy]

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = params[:play_id]
    @review.user_id = current_user.id

    if @review.save
      redirect_to play_path(@play)
    else
      render :new
    end
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private

  def set_play
    @play = Play.find(params[:play_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment, :user_id, :play_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Broadwayapp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if notice.present? || alert.present? %>
  <div aria-live="polite" aria-atomic="true" class="position-relative">
    <div class="toast-container top-0 end-0 p-3">
      <% flash.each do |type, msg| %>
        <div class="toast" role='alert' aria-atomic="true" aria-live="assertive">
          <div class="d-flex">
            <div class="toast-body">
              <div>
                <%= msg %>
              </div>
            </div>
            <button type="button" class="btn-close btn-close-black me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
      <%= link_to 'Broadway', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownmenu1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Sort
            </a>
            <ul class="dropdown-menu m-0" aria-labelledby="dropdownmenu1">
              <li><%= link_to 'All', plays_path, class: "dropdown-item #{'active' unless params[:category].present?}" %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, plays_path(category: category.name), class: "dropdown-item #{'active' if params[:category] == category.name}" %></li>
              <% end %>
            </ul>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Add Play', new_play_path, class: 'btn' %></li>
          <% end %>
        </ul>
        <ul class="navbar-nav d-flex justify-content-between">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn' %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: 'btn' %></li>
            <li class="nav-item"><%= link_to 'Log In', new_user_session_path, class: 'btn' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

<main class="mt-5">
  <div class="container">
    <%= yield %>
  </div>
</main>

</body>
</html>

app/views/plays/_form.html.erb
<% if @play.errors.any? %>
  <% @play.errors.full_messages.each do |message|%>
    <p><%= message %> </p>
  <% end %>
<% end %>

<%= simple_form_for @play, html: { multipart: true } do |f| %>
  <%= f.input :image, as: :file, label: 'Add Image' %>
  <%= f.select :category_id, options_for_select(@categories), { prompt: 'Select Category' }, class: 'form-select' %>
  <%= f.input :title, label: 'Play Title' %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1>Edit Broadway Play</h1>

<%= render 'form' %>

app/views/plays/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @plays.count == 0 %>
  <h3>There are no plays in this category</h3>
<% else %>
 <div class="row">
   <% @plays.each do |play| %>
     <div class="col-md-3">
       <%= link_to play_path(play) do %>
         <% if play.image.attached? %>
           <%= image_tag play.image, class: 'img-fluid' %>
         <% else %>
           <%= image_tag "", alt: "#{play.title} image" %>
         <% end %>
       <% end %>
       <h2><%= link_to play.title, play_path(play) %></h2>
     </div>
   <% end %>
 </div>
<% end %>

<%= link_to 'Add Play', new_play_path %>

app/views/plays/new.html.erb
<h1>New Broadway Play</h1>

<%= render 'form' %>

app/views/plays/show.html.erb
<div class="row">
  <div class="col-md-4">
    <% if @play.image.attached? %>
      <%= image_tag @play.image, class: 'img-fluid' %>
    <% else %>
      <%= image_tag "", alt: "#{@play.title} image" %>
    <% end %>
  </div>
  <div class="col-md-8">
    <div class="play-info">
      <h2 class="play-title"><%= @play.title %></h2>
      <h3 class="play-director"><span>From </span><%= @play.director %></h3>
      <h4 class="play-director"><%= @play.category.name %></h4>
      <p class="avg-rating">Average Rating</p>
      <div class="average-review-rating">
        <% @average_review.to_i.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <%= "<i class='fas fa-star-half'></i>".html_safe if @half_star.present? %>
        <%= @average_review %>
      </div>
      <span class="number-of-reviews"><b>From: </b><%= @play.reviews.count %> reviews</span>
      <p class="play-desc"><%= @play.description %></p>
    </div>
  </div>
</div>
<div class="links btn-group mt-5">
  <%= link_to 'Back', root_path, class: 'btn btn-custom' %>
  <% if user_signed_in? && @play.user_id == current_user.id %>
    <%= link_to 'Edit Play', edit_play_path(@play), class: 'btn btn-custom' %>
    <%= link_to 'Delete', play_path(@play), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-custom' %>
  <% end %>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1><%= @play.reviews.count == 0 ? 'No reviews yet' : 'Reviews' %></h1>
      <%= render @play.reviews %>
      <div>
        <%= link_to 'Add Reviews', new_play_review_path(@play), class: 'btn btn-custom' %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |message|%>
    <p><%= message %> </p>
  <% end %>
<% end %>

<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
    <%= f.select :rating, options_for_select([
                                               ['★★★★★', 5, class: 'fas fa-star' ],
                                               ['★★★★', 4, class: 'fas fa-star' ],
                                               ['★★★', 3, class: 'fas fa-star' ],
                                               ['★★', 2, class: 'fas fa-star' ],
                                               ['★', 1, class: 'fas fa-star' ],
                                             ]), class: 'custom-select' %>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, class: 'btn btn-custom2' %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">
  <% review.rating.to_i.times do %>
    <i class="fas fa-star"></i>
  <% end %>

  <p class="review-comment"><%= review.comment %></p>

  <% if user_signed_in? && review.user_id == current_user.id %>
    <div class="links btn-group">
      <%= link_to 'Edit', edit_play_review_path(review.play, review), class: 'btn btn-custom' %>
      <%= link_to 'Destroy', play_review_path(review.play, review), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-custom' %>
    </div>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="offset-md-1 col-md-10">
  <div class="edit-review-form">
    <% if @review.errors.any? %>
      <% @review.errors.full_messages.each do |message|%>
        <p><%= message %> </p>
      <% end %>
    <% end %>
    <h1>Edit review</h1>
    <%= simple_form_for([@play, @review]) do |f| %>
      <div id="rating-form">
        <label>Rating</label>
        <%= f.select :rating, options_for_select([
                                                   ['★★★★★', 5, class: 'fas fa-star' ],
                                                   ['★★★★', 4, class: 'fas fa-star' ],
                                                   ['★★★', 3, class: 'fas fa-star' ],
                                                   ['★★', 2, class: 'fas fa-star' ],
                                                   ['★', 1, class: 'fas fa-star' ],
                                                 ], @review.rating), class: 'custom-select' %>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, class: 'btn btn-custom2' %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="offset-md-1 col-md-10">
  <div class="new-review-form">
    <h1>Post Review</h1>
    <%= render 'form' %>
  </div>
</div>